---
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/
name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: '42 21 * * 4'
  push:
    branches: [ "master" ]

permissions:
  actions: read
  contents: read

jobs:
  scan-scheduled:
    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c5996e0193a3df57d695c1b8a1dec2a4c62e8730" # v2.3.3
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        ./
