---
name: Tests and checks

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '.circleci/**'
      - '.github/**'
      - '!.github/workflows/tests-and-checks.yml'
      - '.k8s/**'
      - '.vscode/**'
      - '*.md'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          go-version-input: 1.26

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
