---
name: Tests and checks

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '.circleci/**'
      - '.github/**'
      - '!.github/workflows/tests-and-checks.yml'
      - '.k8s/**'
      - '.vscode/**'
      - '*.md'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1
        with:
          go-version-input: 1.26

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
